// <auto-generated />
using System;
using BusTicketsReservation.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusTicketsReservation.Infrastructure.Migrations
{
    [DbContext(typeof(BusReservationContext))]
    [Migration("20240816142117_AddInitData")]
    partial class AddInitData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusTicketsReservation.Domain.Entities.Buses.Bus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 20,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(2542),
                            Type = 2
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 20,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(2560),
                            Type = 1
                        });
                });

            modelBuilder.Entity("BusTicketsReservation.Domain.Entities.Buses.Seat", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeatNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusId = 1,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4566),
                            SeatNumber = "A1"
                        },
                        new
                        {
                            Id = 21,
                            BusId = 2,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4574),
                            SeatNumber = "A1"
                        },
                        new
                        {
                            Id = 2,
                            BusId = 1,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4577),
                            SeatNumber = "A2"
                        },
                        new
                        {
                            Id = 22,
                            BusId = 2,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4578),
                            SeatNumber = "A2"
                        },
                        new
                        {
                            Id = 3,
                            BusId = 1,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4579),
                            SeatNumber = "A3"
                        },
                        new
                        {
                            Id = 23,
                            BusId = 2,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4583),
                            SeatNumber = "A3"
                        },
                        new
                        {
                            Id = 4,
                            BusId = 1,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4585),
                            SeatNumber = "A4"
                        },
                        new
                        {
                            Id = 24,
                            BusId = 2,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4587),
                            SeatNumber = "A4"
                        },
                        new
                        {
                            Id = 5,
                            BusId = 1,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4588),
                            SeatNumber = "A5"
                        },
                        new
                        {
                            Id = 25,
                            BusId = 2,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4590),
                            SeatNumber = "A5"
                        },
                        new
                        {
                            Id = 6,
                            BusId = 1,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4591),
                            SeatNumber = "A6"
                        },
                        new
                        {
                            Id = 26,
                            BusId = 2,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4593),
                            SeatNumber = "A6"
                        },
                        new
                        {
                            Id = 7,
                            BusId = 1,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4594),
                            SeatNumber = "A7"
                        },
                        new
                        {
                            Id = 27,
                            BusId = 2,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4595),
                            SeatNumber = "A7"
                        },
                        new
                        {
                            Id = 8,
                            BusId = 1,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4597),
                            SeatNumber = "A8"
                        },
                        new
                        {
                            Id = 28,
                            BusId = 2,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4598),
                            SeatNumber = "A8"
                        },
                        new
                        {
                            Id = 9,
                            BusId = 1,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4599),
                            SeatNumber = "A9"
                        },
                        new
                        {
                            Id = 29,
                            BusId = 2,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4601),
                            SeatNumber = "A9"
                        },
                        new
                        {
                            Id = 10,
                            BusId = 1,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4605),
                            SeatNumber = "A10"
                        },
                        new
                        {
                            Id = 30,
                            BusId = 2,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4607),
                            SeatNumber = "A10"
                        },
                        new
                        {
                            Id = 11,
                            BusId = 1,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4608),
                            SeatNumber = "A11"
                        },
                        new
                        {
                            Id = 31,
                            BusId = 2,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4609),
                            SeatNumber = "A11"
                        },
                        new
                        {
                            Id = 12,
                            BusId = 1,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4611),
                            SeatNumber = "A12"
                        },
                        new
                        {
                            Id = 32,
                            BusId = 2,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4612),
                            SeatNumber = "A12"
                        },
                        new
                        {
                            Id = 13,
                            BusId = 1,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4613),
                            SeatNumber = "A13"
                        },
                        new
                        {
                            Id = 33,
                            BusId = 2,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4614),
                            SeatNumber = "A13"
                        },
                        new
                        {
                            Id = 14,
                            BusId = 1,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4616),
                            SeatNumber = "A14"
                        },
                        new
                        {
                            Id = 34,
                            BusId = 2,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4617),
                            SeatNumber = "A14"
                        },
                        new
                        {
                            Id = 15,
                            BusId = 1,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4618),
                            SeatNumber = "A15"
                        },
                        new
                        {
                            Id = 35,
                            BusId = 2,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4620),
                            SeatNumber = "A15"
                        },
                        new
                        {
                            Id = 16,
                            BusId = 1,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4621),
                            SeatNumber = "A16"
                        },
                        new
                        {
                            Id = 36,
                            BusId = 2,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4622),
                            SeatNumber = "A16"
                        },
                        new
                        {
                            Id = 17,
                            BusId = 1,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4623),
                            SeatNumber = "A17"
                        },
                        new
                        {
                            Id = 37,
                            BusId = 2,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4626),
                            SeatNumber = "A17"
                        },
                        new
                        {
                            Id = 18,
                            BusId = 1,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4627),
                            SeatNumber = "A18"
                        },
                        new
                        {
                            Id = 38,
                            BusId = 2,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4629),
                            SeatNumber = "A18"
                        },
                        new
                        {
                            Id = 19,
                            BusId = 1,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4630),
                            SeatNumber = "A19"
                        },
                        new
                        {
                            Id = 39,
                            BusId = 2,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4631),
                            SeatNumber = "A19"
                        },
                        new
                        {
                            Id = 20,
                            BusId = 1,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4633),
                            SeatNumber = "A20"
                        },
                        new
                        {
                            Id = 40,
                            BusId = 2,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(4634),
                            SeatNumber = "A20"
                        });
                });

            modelBuilder.Entity("BusTicketsReservation.Domain.Entities.Reservations.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReservationTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("BusTicketsReservation.Domain.Entities.Trips.Trip", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<string>("Route")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusId = 1,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(6123),
                            Distance = 90.0,
                            Route = "Cairo-Alexandria"
                        },
                        new
                        {
                            Id = 2,
                            BusId = 2,
                            CreatedDate = new DateTime(2024, 8, 16, 14, 21, 17, 116, DateTimeKind.Utc).AddTicks(6130),
                            Distance = 150.0,
                            Route = "Cairo-Aswan"
                        });
                });

            modelBuilder.Entity("BusTicketsReservation.Domain.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BusTicketsReservation.Domain.Entities.Buses.Seat", b =>
                {
                    b.HasOne("BusTicketsReservation.Domain.Entities.Buses.Bus", "Bus")
                        .WithMany("Seats")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("BusTicketsReservation.Domain.Entities.Reservations.Reservation", b =>
                {
                    b.HasOne("BusTicketsReservation.Domain.Entities.Buses.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusTicketsReservation.Domain.Entities.Trips.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusTicketsReservation.Domain.Entities.Users.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusTicketsReservation.Domain.Entities.Trips.Trip", b =>
                {
                    b.HasOne("BusTicketsReservation.Domain.Entities.Buses.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("BusTicketsReservation.Domain.Entities.Buses.Bus", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("BusTicketsReservation.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
